In [2]:
import os

# Set working directory to project root
os.chdir("D:/Projects/Skincare_Analyzer")

# Verify it worked
print(os.getcwd())

D:\Projects\Skincare_Analyzer

In [3]:
import pandas as pd

# Load product_info.csv file from raw
df = pd.read_csv("data/raw/product_info.csv")

# Print shape (rows, columns)
print(df.shape)

# Print column names
print(df.columns)

# Print first 5 rows
df.head(5)

(8494, 27)
Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price'],
      dtype='object')

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P473671,Fragrance Discovery Set,6342,19-69,6320,3.6364,11.0,NaN,NaN,NaN,...,1,0,0,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342,19-69,3827,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,85.0,30.0
2,P473662,Rainbow Bar Eau de Parfum,6342,19-69,3253,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
3,P473660,Kasbah Eau de Parfum,6342,19-69,3018,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
4,P473658,Purple Haze Eau de Parfum,6342,19-69,2691,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0

In [4]:
# How many products per category?
print(df['primary_category'].value_counts())
print('---')
# How many missing ingredients?
print(df['ingredients'].isna().sum())
print('---')
# How many skincare products specifically?
print(df[df['primary_category'] == 'Skincare'].shape)
print('---')

primary_category
Skincare           2420
Makeup             2369
Hair               1464
Fragrance          1432
Bath & Body         405
Mini Size           288
Men                  60
Tools & Brushes      52
Gifts                 4
Name: count, dtype: int64
---
945
---
(2420, 27)
---

In [5]:
# Skincare DF
skincare_df = df[df['primary_category'] == 'Skincare'].copy()

In [6]:
skincare_df

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
89,P439055,GENIUS Sleeping Collagen Moisturizer,6018,Algenist,33910,4.5413,1321.0,2 oz/ 60 mL,Size,2 oz/ 60 mL,...,0,0,1,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Skincare,Moisturizers,Moisturizers,0,NaN,NaN
90,P421277,GENIUS Liquid Collagen Serum,6018,Algenist,67870,4.0259,1159.0,1 oz / 30 mL,Size,1 oz / 30 mL,...,0,0,1,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Skincare,Treatments,Face Serums,1,25.0,25.0
91,P467602,Triple Algae Eye Renewal Balm Eye Cream,6018,Algenist,17890,4.5306,1142.0,NaN,NaN,NaN,...,0,0,1,NaN,Skincare,Eye Care,Eye Creams & Treatments,0,NaN,NaN
92,P432045,GENIUS Liquid Collagen Lip Treatment,6018,Algenist,44448,3.8721,649.0,.5 oz / 15 mL,Size,.5 oz / 15 mL,...,0,0,1,"['Vegan', 'Good for: Loss of firmness', 'Plump...",Skincare,Lip Balms & Treatments,NaN,0,NaN,NaN
93,P311143,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,6018,Algenist,27278,4.4134,508.0,1 oz,Size,1 oz,...,0,0,0,"['Vegan', 'Hypoallergenic', 'UV Protection', '...",Skincare,Sunscreen,Face Sunscreen,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8424,P501474,The Youth Vault: 13-Piece Vegan Skincare + App...,6169,Youth To The People,8989,4.8750,8.0,NaN,NaN,NaN,...,1,0,1,"['Clean at Sephora', 'Hydrating', 'Good for: A...",Skincare,Value & Gift Sets,NaN,0,NaN,NaN
8425,P502998,"Youth Stacks: Plump It Up for Dry, Dehydrated ...",6169,Youth To The People,10406,4.1667,6.0,NaN,NaN,NaN,...,0,0,0,"['Vegan', 'Hyaluronic Acid', 'Clean at Sephora...",Skincare,Value & Gift Sets,NaN,0,NaN,NaN
8426,P503872,Mini Mandelic Acid + Superfood Unity Exfoliant,6169,Youth To The People,6510,4.8000,5.0,1 oz / 30 mL,Size,1 oz / 30 mL,...,0,0,0,"['Clean + Planet Positive', 'Good for: Pores',...",Skincare,Cleansers,Toners,0,NaN,NaN
8427,P502977,Youth Stacks: Daily Skin Health Your Way for P...,6169,Youth To The People,13592,4.2500,4.0,NaN,NaN,NaN,...,0,0,0,"['Vegan', 'Good for: Pores', 'Clean + Planet P...",Skincare,Value & Gift Sets,NaN,0,NaN,NaN
8428,P502978,Youth Stacks: Brighter Tomorrow Duo for Dullness,6169,Youth To The People,8189,3.0000,3.0,NaN,NaN,NaN,...,0,0,0,"['Vegan', 'Good for: Dullness/Uneven Texture',...",Skincare,Value & Gift Sets,NaN,0,NaN,NaN

In [7]:
# Total Skincare
print(len(skincare_df))

2420

In [8]:
# Total missing ingredients in skincare_df
print(skincare_df['ingredients'].isna().sum())

134

In [9]:
# Skincare with ingredients
print(skincare_df['ingredients'].notna().sum())

2286

In [10]:
2420-134

2286

In [11]:
# We can remove 134 NA as it constitutes extremely less and won't affect the data after removal

In [12]:
# Check the Skincare subcategories that we have
print(skincare_df['secondary_category'].value_counts())

secondary_category
Moisturizers              551
Treatments                466
Cleansers                 361
Value & Gift Sets         196
Eye Care                  186
Masks                     166
Mini Size                 112
Sunscreen                 108
High Tech Tools            80
Wellness                   79
Lip Balms & Treatments     61
Self Tanners               53
Shop by Concern             1
Name: count, dtype: int64

In [13]:
# Real ingredient list
print(skincare_df['ingredients'].iloc[0])

['Collagen (Vegan)*, Water (Aqua, Eau), Ethylhexyl Palmitate, Oryza Sativa (Rice) Bran Extract, Caprylic/Capric Triglyceride, Glycerin, Cetearyl Methicone, Dimethicone, Cetearyl Alcohol, Pyrus Malus (Apple) Fruit Extract, Chlorella Protothecoides Oil, Polysorbate 60, Glyceryl Glucoside , Polyglyceryl-2 Stearate, Parachlorella Beijerinckii Exopolysaccharides, Collagen Amino Acids (Vegan)*, Ceramide NP, Silybum Marianum Fruit Extract, Helianthus Annuus (Sunflower) Extract, Rosmarinus Officinalis (Rosemary) Leaf Extract, Tocopherol, Carnosine, Sodium Stearoyl Glutamate, Caprylyl Glycol, Ammonium Acryloyldimethyltaurate/VP Copolymer, Ethylhexylglycerin, Hexylene Glycol, Citric Acid, Lecithin, Sodium Hydroxide, Sodium Phytate, t-Butyl Alcohol, Leuconostoc/Radish Root Ferment Filtrate, Phenoxyethanol, Triethyl Citrate, Vanillin, Amyl Salicylate, Benzyl Acetate, Cedrus Atlantica Bark Oil, Phenethyl Alcohol, Ionone, Linalool.']

In [14]:
# Highlights
print(skincare_df['highlights'].iloc[0])

['Vegan', 'Good for: Loss of firmness', 'Collagen', 'Hypoallergenic', 'Without Parabens', 'Best for Dry, Combo, Normal Skin']

In [15]:
# Check how many unique highlights/skin type tag exist
import ast

# Get all highlights as lists and flatten
all_highlights = []
for val in skincare_df['highlights'].dropna():
    try:
        items = ast.literal_eval(val)
        all_highlights.extend(items)
    except:
        pass

# Most common highlights
import pandas as pd
pd.Series(all_highlights).value_counts().head(20)

Good for: Dullness/Uneven Texture    744
Clean at Sephora                     741
Vegan                                689
Good for: Dryness                    603
Cruelty-Free                         579
Good for: Anti-Aging                 574
Hydrating                            432
Without Parabens                     419
Good for: Loss of firmness           393
Hyaluronic Acid                      393
Best for Dry, Combo, Normal Skin     377
Good for: Pores                      323
Clean + Planet Positive              307
Best for Oily, Combo, Normal Skin    287
Fragrance Free                       283
Without Sulfates SLS & SLES          219
Vitamin C                            216
Good for: Dark Circles               203
Good for: Acne/Blemishes             202
Good for: Dark spots                 162
Name: count, dtype: int64