In [1]:
import os
os.chdir("D:/Projects/Skincare_Analyzer")

In [2]:
irritants = [
    'fragrance', 'parfum', 'alcohol denat', 'denatured alcohol',
    'limonene', 'linalool', 'citral', 'eugenol', 'geraniol',
    'cinnamal', 'benzyl alcohol', 'isopropyl alcohol',
    'menthol', 'sodium lauryl sulfate', 'citronellol'
]

comedogenic = [
    'coconut oil', 'cocoa butter', 'isopropyl myristate',
    'isopropyl palmitate', 'acetylated lanolin', 'wheat germ oil',
    'flaxseed oil', 'soybean oil', 'cottonseed oil'
]

harmful = [
    'parabens', 'methylparaben', 'propylparaben', 'butylparaben',
    'formaldehyde', 'dmdm hydantoin', 'quaternium-15',
    'triclosan', 'sodium lauryl sulfate', 'polyethylene',
    'butylated hydroxyanisole', 'bha', 'bht'
]

beneficial = [
    'niacinamide', 'retinol', 'retinyl palmitate', 'hyaluronic acid',
    'sodium hyaluronate', 'glycerin', 'ceramide np', 'ceramide ap',
    'ceramide eop', 'squalane', 'tocopherol', 'tocopheryl acetate',
    'ascorbic acid', 'vitamin c', 'panthenol', 'allantoin',
    'centella asiatica', 'salicylic acid', 'lactic acid',
    'glycolic acid', 'azelaic acid', 'caffeine', 'peptides',
    'collagen', 'aloe barbadensis leaf juice'
]

In [3]:
import pandas as pd
import ast

In [4]:
skincare_df = pd.read_csv('data/processed/skincare_df.csv')

In [5]:
skincare_df['ingredient_list']

0       ['collagen (vegan)', 'water (aqua, eau)', 'eth...
1       ['collagen (vegan)', 'water (aqua, eau)', 'pro...
2       ['aqua (water/eau)', 'stearic acid', 'isopropy...
3       ['collagen (vegan)', 'water (aqua, eau)', 'gly...
4       ['octinoxate 7.5%', 'titanium dioxide 2%', 'zi...
                              ...
2281    ['superfood antioxidant cleanser:', 'water/aqu...
2282    ['triple peptide + cactus oasis serum:', 'wate...
2283    ['water/aqua/eau (aqua)', 'helianthus annuus (...
2284    ['superfood antioxidant cleanser:', 'water/aqu...
2285    ['15% vitamin c + caffeine energy serum:', 'wa...
Name: ingredient_list, Length: 2286, dtype: object

In [6]:
def analyze_ingredients(ingredient_list):
    found_irritants = [i for i in irritants if i in ingredient_list]
    found_comedogenic = [i for i in comedogenic if i in ingredient_list]
    found_harmful = [i for i in harmful if i in ingredient_list]
    found_beneficial = [i for i in beneficial if i in ingredient_list]
    return {
        'irritants' : found_irritants,
        'comedogenic' : found_comedogenic,
        'harmful' : found_harmful,
        'beneficial' : found_beneficial
    }

result = analyze_ingredients(skincare_df['ingredient_list'].iloc[0])
print(result)

{'irritants': ['linalool'], 'comedogenic': [], 'harmful': [], 'beneficial': ['glycerin', 'ceramide np', 'tocopherol', 'collagen']}

In [7]:
skincare_df.head(2)

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,ingredients,price_usd,highlights,primary_category,secondary_category,tertiary_category,ingredient_list,highlights_list
0,P439055,GENIUS Sleeping Collagen Moisturizer,6018,Algenist,33910,4.5413,1321.0,2 oz/ 60 mL,"['Collagen (Vegan)*, Water (Aqua, Eau), Ethylh...",98.0,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Skincare,Moisturizers,Moisturizers,"['collagen (vegan)', 'water (aqua, eau)', 'eth...","['Vegan', 'Good for: Loss of firmness', 'Colla..."
1,P421277,GENIUS Liquid Collagen Serum,6018,Algenist,67870,4.0259,1159.0,1 oz / 30 mL,"['Collagen (Vegan)*, Water (Aqua, Eau), Propan...",115.0,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Skincare,Treatments,Face Serums,"['collagen (vegan)', 'water (aqua, eau)', 'pro...","['Vegan', 'Good for: Loss of firmness', 'Colla..."

In [8]:
# Apply analyze_ingredients() to dataset
analysis = skincare_df['ingredient_list'].apply(analyze_ingredients)

# Split it into separate columns
skincare_df['irritants_found'] = analysis.apply(lambda x:x['irritants'])
skincare_df['comedogenic_found'] = analysis.apply(lambda x:x['comedogenic'])
skincare_df['harmful_found'] = analysis.apply(lambda x:x['harmful'])
skincare_df['beneficial_found'] = analysis.apply(lambda x:x['beneficial'])

# Check result
skincare_df[['product_name','irritants_found','comedogenic_found','harmful_found','beneficial_found']].head(5)

,product_name,irritants_found,comedogenic_found,harmful_found,beneficial_found
0,GENIUS Sleeping Collagen Moisturizer,[linalool],[],[],"[glycerin, ceramide np, tocopherol, collagen]"
1,GENIUS Liquid Collagen Serum,"[fragrance, parfum, limonene]",[],[],"[niacinamide, glycerin, tocopherol, collagen]"
2,Triple Algae Eye Renewal Balm Eye Cream,[benzyl alcohol],[],[],"[sodium hyaluronate, glycerin, tocopheryl acet..."
3,GENIUS Liquid Collagen Lip Treatment,[],[],[],"[glycerin, tocopherol, collagen]"
4,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,"[fragrance, parfum, alcohol denat, linalool, c...",[],[bht],"[glycerin, tocopheryl acetate]"

In [9]:
skincare_df.to_csv('data/processed/skincare_knowledge.csv', index = False)
print('Saved!')
print(skincare_df.shape)

Saved!
(2286, 20)