In [1]:
import os
os.chdir("D:/Projects/Skincare_Analyzer")

In [2]:
import pandas as pd
import ast

In [3]:
skincare_df = pd.read_csv("data/processed/skincare_knowledge.csv")

In [4]:
skincare_df.columns

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'ingredients', 'price_usd', 'highlights',
       'primary_category', 'secondary_category', 'tertiary_category',
       'ingredient_list', 'highlights_list', 'irritants_found',
       'comedogenic_found', 'harmful_found', 'beneficial_found'],
      dtype='object')

In [5]:
skincare_df['irritants_found']

0                                            ['linalool']
1                     ['fragrance', 'parfum', 'limonene']
2                                      ['benzyl alcohol']
3                                                      []
4       ['fragrance', 'parfum', 'alcohol denat', 'lina...
                              ...
2281    ['fragrance', 'parfum', 'limonene', 'linalool'...
2282                                   ['benzyl alcohol']
2283    ['fragrance', 'limonene', 'linalool', 'cinnama...
2284    ['fragrance', 'parfum', 'limonene', 'linalool'...
2285                                         ['limonene']
Name: irritants_found, Length: 2286, dtype: object

In [6]:
# Convert list columns back to real list
skincare_df['ingredient_list'] = skincare_df['ingredient_list'].apply(ast.literal_eval)
skincare_df['irritants_found'] = skincare_df['irritants_found'].apply(ast.literal_eval)
skincare_df['comedogenic_found'] = skincare_df['comedogenic_found'].apply(ast.literal_eval)
skincare_df['harmful_found'] = skincare_df['harmful_found'].apply(ast.literal_eval)
skincare_df['beneficial_found'] = skincare_df['beneficial_found'].apply(ast.literal_eval)

In [7]:
skincare_df['irritants_found']

0                                              [linalool]
1                           [fragrance, parfum, limonene]
2                                        [benzyl alcohol]
3                                                      []
4       [fragrance, parfum, alcohol denat, linalool, c...
                              ...
2281    [fragrance, parfum, limonene, linalool, cinnam...
2282                                     [benzyl alcohol]
2283    [fragrance, limonene, linalool, cinnamal, citr...
2284    [fragrance, parfum, limonene, linalool, cinnam...
2285                                           [limonene]
Name: irritants_found, Length: 2286, dtype: object

In [8]:
skincare_df.columns

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'ingredients', 'price_usd', 'highlights',
       'primary_category', 'secondary_category', 'tertiary_category',
       'ingredient_list', 'highlights_list', 'irritants_found',
       'comedogenic_found', 'harmful_found', 'beneficial_found'],
      dtype='object')

In [9]:
# Count features - how many of each type per product
skincare_df['total_ingredients'] = skincare_df['ingredient_list'].apply(len)
skincare_df['irritants_count'] = skincare_df['irritants_found'].apply(len)
skincare_df['comedogenic_count'] = skincare_df['comedogenic_found'].apply(len)
skincare_df['harmful_count'] = skincare_df['harmful_found'].apply(len)
skincare_df['beneficial_count'] = skincare_df['beneficial_found'].apply(len)

In [10]:
skincare_df['total_ingredients']

0        42
1        39
2        64
3        37
4        28
       ...
2281    437
2282     79
2283     32
2284     74
2285     68
Name: total_ingredients, Length: 2286, dtype: int64

In [11]:
# Ratio features
skincare_df['irritants_ratio'] = skincare_df['irritants_count'] / skincare_df['total_ingredients']
skincare_df['comedogenic_ratio'] = skincare_df['comedogenic_count'] / skincare_df['total_ingredients']
skincare_df['harmful_ratio'] = skincare_df['harmful_count'] / skincare_df['total_ingredients']
skincare_df['beneficial_ratio'] = skincare_df['beneficial_count'] / skincare_df['total_ingredients']

In [12]:
# Check results
skincare_df[['product_name','total_ingredients','irritants_count','irritants_ratio','beneficial_count','beneficial_ratio']].head()

,product_name,total_ingredients,irritants_count,irritants_ratio,beneficial_count,beneficial_ratio
0,GENIUS Sleeping Collagen Moisturizer,42,1,0.023810,4,0.095238
1,GENIUS Liquid Collagen Serum,39,3,0.076923,4,0.102564
2,Triple Algae Eye Renewal Balm Eye Cream,64,1,0.015625,7,0.109375
3,GENIUS Liquid Collagen Lip Treatment,37,0,0.000000,3,0.081081
4,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,28,5,0.178571,2,0.071429

In [13]:
# Binary features - 0 or 1
skincare_df['has_fragrance'] = skincare_df['ingredient_list'].apply(lambda x:1 if 'fragrance' in x or 'parfum' in x else 0)
skincare_df['has_alcohol'] = skincare_df['ingredient_list'].apply(lambda x:1 if 'alcohol denat' in x else 0)

skincare_df['has_harmful'] = skincare_df['harmful_found'].apply(lambda x:1 if len(x) > 0 else 0)
skincare_df['has_beneficial'] = skincare_df['beneficial_found'].apply(lambda x: 1 if len(x) > 0 else 0)

skincare_df[['product_name', 'has_fragrance', 'has_alcohol', 
             'has_harmful', 'has_beneficial']].head()

,product_name,has_fragrance,has_alcohol,has_harmful,has_beneficial
0,GENIUS Sleeping Collagen Moisturizer,0,0,0,1
1,GENIUS Liquid Collagen Serum,0,0,0,1
2,Triple Algae Eye Renewal Balm Eye Cream,0,0,0,1
3,GENIUS Liquid Collagen Lip Treatment,0,0,0,1
4,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,0,1,1,1

In [15]:
skincare_df

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,ingredients,price_usd,...,harmful_count,beneficial_count,irritants_ratio,comedogenic_ratio,harmful_ratio,beneficial_ratio,has_fragrance,has_alcohol,has_harmful,has_beneficial
0,P439055,GENIUS Sleeping Collagen Moisturizer,6018,Algenist,33910,4.5413,1321.0,2 oz/ 60 mL,"['Collagen (Vegan)*, Water (Aqua, Eau), Ethylh...",98.0,...,0,4,0.023810,0.000000,0.000000,0.095238,0,0,0,1
1,P421277,GENIUS Liquid Collagen Serum,6018,Algenist,67870,4.0259,1159.0,1 oz / 30 mL,"['Collagen (Vegan)*, Water (Aqua, Eau), Propan...",115.0,...,0,4,0.076923,0.000000,0.000000,0.102564,0,0,0,1
2,P467602,Triple Algae Eye Renewal Balm Eye Cream,6018,Algenist,17890,4.5306,1142.0,NaN,"['Aqua (Water/Eau), Stearic Acid, Isopropyl Is...",68.0,...,0,7,0.015625,0.000000,0.000000,0.109375,0,0,0,1
3,P432045,GENIUS Liquid Collagen Lip Treatment,6018,Algenist,44448,3.8721,649.0,.5 oz / 15 mL,"['Collagen (Vegan)*, Water (Aqua, Eau), Glycer...",29.0,...,0,3,0.000000,0.000000,0.000000,0.081081,0,0,0,1
4,P311143,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,6018,Algenist,27278,4.4134,508.0,1 oz,"['Octinoxate 7.5%, Titanium Dioxide 2%, Zinc O...",28.0,...,1,2,0.178571,0.000000,0.035714,0.071429,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2281,P501474,The Youth Vault: 13-Piece Vegan Skincare + App...,6169,Youth To The People,8989,4.8750,8.0,NaN,"['Superfood Antioxidant Cleanser:', 'Water/Aqu...",340.0,...,0,17,0.018307,0.002288,0.000000,0.038902,0,0,0,1
2282,P502998,"Youth Stacks: Plump It Up for Dry, Dehydrated ...",6169,Youth To The People,10406,4.1667,6.0,NaN,"['Triple Peptide + Cactus Oasis Serum:', 'Wate...",28.0,...,0,7,0.012658,0.000000,0.000000,0.088608,0,0,0,1
2283,P503872,Mini Mandelic Acid + Superfood Unity Exfoliant,6169,Youth To The People,6510,4.8000,5.0,1 oz / 30 mL,"['Water/Aqua/Eau (Aqua), Helianthus Annuus (Su...",16.0,...,0,6,0.156250,0.000000,0.000000,0.187500,0,0,0,1
2284,P502977,Youth Stacks: Daily Skin Health Your Way for P...,6169,Youth To The People,13592,4.2500,4.0,NaN,"['Superfood Antioxidant Cleanser:', 'Water/Aqu...",20.0,...,0,8,0.094595,0.000000,0.000000,0.108108,0,0,0,1
2285,P502978,Youth Stacks: Brighter Tomorrow Duo for Dullness,6169,Youth To The People,8189,3.0000,3.0,NaN,"['15% Vitamin C + Caffeine Energy Serum:', 'Wa...",28.0,...,0,11,0.014706,0.014706,0.000000,0.161765,0,0,0,1

In [16]:
skincare_df['highlights_list'] = skincare_df['highlights_list'].apply(ast.literal_eval)

# Target labels
skincare_df['is_for_dry_skin']  = skincare_df['highlights_list'].apply(lambda x: 1 if 'Best for Dry, Combo, Normal Skin' in x else 0)

skincare_df['is_for_oily_skin'] = skincare_df['highlights_list'].apply(lambda x: 1 if 'Best for Oily, Combo, Normal Skin' in x else 0)

# 1 if good for acne, else 0
skincare_df['is_good_for_acne'] = skincare_df['highlights_list'].apply(lambda x:1 if 'Good for: Acne/Blemishes' in x else 0)
# 1 if fragrance free, else 0
skincare_df['is_fragrance_free'] = skincare_df['highlights_list'].apply(lambda x:1 if 'Fragrance Free' in x else 0)

skincare_df[['product_name', 'is_for_dry_skin', 'is_for_oily_skin', 'is_good_for_acne', 'is_fragrance_free']].head(10)

,product_name,is_for_dry_skin,is_for_oily_skin,is_good_for_acne,is_fragrance_free
0,GENIUS Sleeping Collagen Moisturizer,1,0,0,0
1,GENIUS Liquid Collagen Serum,1,0,0,0
2,Triple Algae Eye Renewal Balm Eye Cream,0,0,0,0
3,GENIUS Liquid Collagen Lip Treatment,1,0,0,0
4,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,1,0,0,0
5,GENIUS Ultimate Anti-Aging Cream,1,0,0,0
6,GENIUS Ultimate Anti-Aging Melting Cleanser,0,0,0,0
7,Gentle Rejuvenating Cleanser,0,0,0,0
8,10 Day Results Kit,0,0,0,0
9,Advanced Anti-Aging Repairing Oil,0,0,0,0

In [17]:
skincare_df.to_csv("data/processed/skincare_features.csv", index=False)
print("Saved!")
print(skincare_df.shape)
print(skincare_df.columns.tolist())

Saved!
(2286, 37)
['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count', 'rating', 'reviews', 'size', 'ingredients', 'price_usd', 'highlights', 'primary_category', 'secondary_category', 'tertiary_category', 'ingredient_list', 'highlights_list', 'irritants_found', 'comedogenic_found', 'harmful_found', 'beneficial_found', 'total_ingredients', 'irritants_count', 'comedogenic_count', 'harmful_count', 'beneficial_count', 'irritants_ratio', 'comedogenic_ratio', 'harmful_ratio', 'beneficial_ratio', 'has_fragrance', 'has_alcohol', 'has_harmful', 'has_beneficial', 'is_for_dry_skin', 'is_for_oily_skin', 'is_good_for_acne', 'is_fragrance_free']